-- MySQL Script generated by MySQL Workbench
-- Пн 29 ноя 2021 15:24:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cryptocompare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cryptocompare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cryptocompare` DEFAULT CHARACTER SET utf8 ;
USE `cryptocompare` ;

-- -----------------------------------------------------
-- Table `cryptocompare`.`fsym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cryptocompare`.`fsym` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(5) NULL,
  `unicode` CHAR(1) NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cryptocompare`.`tsym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cryptocompare`.`tsym` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(5) NULL,
  `unicode` CHAR(1) NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cryptocompare`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cryptocompare`.`data` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `fromSym` INT NOT NULL,
  `toSym` INT NOT NULL,
  `change24hour` DOUBLE NULL,
  `changepct24hour` DOUBLE NULL,
  `open24hour` DOUBLE NULL,
  `volume24hour` DOUBLE NULL,
  `low24hour` DOUBLE NULL,
  `high24hour` DOUBLE NULL,
  `price` DOUBLE NULL,
  `supply` DOUBLE NULL,
  `mktcap` DOUBLE NULL,
  `lastupdate` MEDIUMTEXT NOT NULL,
  `displaydataraw` TEXT NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_tsym_idx` (`toSym` ASC),
  INDEX `fk_fsym_idx` (`fromSym` ASC),
  CONSTRAINT `fk_fsym`
    FOREIGN KEY (`fromSym`)
    REFERENCES `cryptocompare`.`fsym` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tsym`
    FOREIGN KEY (`toSym`)
    REFERENCES `cryptocompare`.`tsym` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
