name: releaser
on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push_to_registry:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.1
      with:
        images: |
          streamdp/ccd
          ghcr.io/streamdp/ccd
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: VERSION=${{ steps.meta.outputs.labels }}
