name: releaser
on:
  push:
    tags: ['*']
jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: 1.24.2
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6.3.0
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: v2
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push_to_the_registry:
    needs: [goreleaser]
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4.1.7
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.2.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
    - name: Docker Scout
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ github.repository }}:latest
        only-severities: critical,high
        exit-code: true